Products/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^product_list/', views.product_list_view, name='product_list_view'),
    url(r'^product_list/(?P<category_slug>[-\w]+)/$', views.product_list_view, name='product_list_view_by_category'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    
    
]

billing/urls.py
from django.conf.urls import url
from django.utils.translation import gettext_lazy as _
from . import views


urlpatterns = [
    url(_(r'^process/$'), views.payment_process, name='process'),
    url(_(r'^done/$'), views.payment_done, name='done'),
    url(_(r'^canceled/$'), views.payment_canceled, name='canceled'),
]

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_home, name='cart'),
    url(r'^update/$', views.cart_update, name='update'),
    url(r'^add/$', views.cart_add, name='add'),
    url(r'^cart/$', views.cart_remove, name='delate'),
    url(r'^wishlist/$', views.wishlist, name='wishlist'),

]

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.overview, name='overview'),
  
]

stylelure/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from shop import views
from accounts import views as accounts_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from addresses.views import checkout_address_create_view,address_update
from orders.views import overview
# from cart.views import checkout_home
from coupons.views import coupon_apply


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^account/',include('accounts.urls',namespace='accounts')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^contact/$', views.emailView, name='contact'),
    url(r'^address/$', address_update, name='address'),
    url(r'^address/add$', checkout_address_create_view, name='add_address'),
    url(r'^order/',include('orders.urls',namespace='order')),
    #url(r'^order/overview$', checkout_home, name='overview'),
    url(r'^apply/$',coupon_apply, name='apply'),
    url(r'^payment/',include('billing.urls',namespace='payment')),
    url(r'^contact/success$', views.successView, name='success'),
    url(r'^product/',include('Products.urls',namespace='Products')),
    url(r'^search/',include('search.urls',namespace='search')),
    # url(r'^review/', include('review.urls')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^wishlist/',include('wishlist.urls',namespace='wishlist')),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billing/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save

User = settings.AUTH_USER_MODEL


class BillingProfileManager(models.Manager):
    def new_or_get(self, request):
        user = request.user
        guest_email_id = request.session.get('guest_email_id')
        created = False
        obj = None
        if user.is_authenticated():
            'logged in user checkout; remember payment stuff'
            obj, created = self.model.objects.get_or_create(
                            user=user, email=user.email)
        elif guest_email_id is not None:
            'guest user checkout; auto reloads payment stuff'
            guest_email_obj = GuestEmail.objects.get(id=guest_email_id)
            obj, created = self.model.objects.get_or_create(
                                            email=guest_email_obj.email)
        else:
            pass
        return obj, created

class BillingProfile(models.Model):
    user        = models.OneToOneField(User,related_name='user', null=True, blank=True,on_delete=models.CASCADE)
    email       = models.EmailField()
    active      = models.BooleanField(default=True)
    update      = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = BillingProfileManager()

    def __str__(self):
        return self.email


def user_created_receiver(sender, instance, created, *args, **kwargs):
    if created and instance.email:
        BillingProfile.objects.get_or_create(user=instance, email=instance.email)

post_save.connect(user_created_receiver, sender=User)

billing/views.py
from django.shortcuts import render
from .models import BillingProfile
from decimal import Decimal
from django.conf import settings
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from orders.models import Order
from django.views.decorators.csrf import csrf_exempt
from cart.models import Cart
from billing.models import BillingProfile
from orders.models import Order
from datetime import datetime


@csrf_exempt
def payment_done(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
    order_obj.updated=datetime.now()
    order_obj.save()
    # order_obj.status='paid'
    # order_obj.save()
    # cart_obj.delete()
    #import pdb; pdb.set_trace()
    context = {
            "object": order_obj,
            "billing_profile": billing_profile,
        }
    return render(request, 'payment/done.html',context)


@csrf_exempt
def payment_canceled(request):
    return render(request, 'payment/canceled.html')


def payment_process(request):
    pass

# Create your views here.

billing/templates/payment/canceled.html
{% extends "base.html" %}


{% block content %}
    <h1> "Your payment has not been processed" </h1>
    <p>"There was a problem processing your payment."</p>
{% endblock %}

billing/templates/payment/done.html
{% extends "base_account.html" %}


{% block content %}
<div class="banner inner-banner1 ">
  <div class="container">
    <section class="banner-detail center-xs">
      <h1 class="banner-title">Checkout</h1>
      <div class="bread-crumb right-side float-none-xs">
        <ul>
          <li><a href="index.html">Home</a>/</li>
          <li><a href="cart.html">Cart</a>/</li>
          <li><span>Checkout</span></li>
        </ul>
      </div>
    </section>
  </div>
</div>

<section class="checkout-section ptb-70">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="checkout-step mb-40">
          <ul>
            <li>
                <a href="{% url 'address' %}">
                <div class="step">
                  <div class="line"></div>
                  <div class="circle">1</div>
                </div>
                <span>Shipping</span>
              </a>
            </li>
            <li >
              <a href="{% url 'order:overview' %}">
                <div class="step">
                  <div class="line"></div>
                  <div class="circle">2</div>
                </div>
                <span>Order Overview</span>
              </a>
            </li>
            <li>
              <a href="{% url 'payment:process' %}">
                <div class="step">
                  <div class="line"></div>
                  <div class="circle">3</div>
                </div>
                <span>Payment</span>
              </a>
            </li>
            <li class="active">
              <a href="{% url 'payment:done' %}">
                <div class="step">
                  <div class="line"></div>
                  <div class="circle">4</div>
                </div>
                <span>Order Complete</span>
              </a>
            </li>
            <li>
              <div class="step">
                <div class="line"></div>
              </div>
            </li>
          </ul>
         <hr>
        </div>
        <div class="checkout-content">
          <div class="row">
            <div class="col-12">
              <div class="heading-part align-center">
                <h2 class="heading">Order Overview</h2>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-8 mb-sm-30">
              <div id="form-print" class="admission-form-wrapper">
                <div class="cart-item-table complete-order-table commun-table mb-30">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Product</th>
                          <th>Product Detail</th>
                        </tr>
                      </thead>
                      <tbody>

                          {% for item in object.cart.items.all %}
                        <tr>
                          <td>
                            <a href="{{item.product.get_absolute_url}}">
                              <div class="product-image">
                                <img alt="Stylelure" src="{{ item.product.images.first.image.url }}">
                              </div>
                            </a>
                          </td>
                          <td>
                            <div class="product-title">
                              <a href="{{item.product.get_absolute_url}}">{{item.product.title|truncatechars:25}}</a>
                              <div class="product-info-stock-sku m-0">
                                <div>
                                  <label>Price: </label>
                                  <div class="price-box">
                                    <span class="info-deta price">${{ item.product.discounted_price|floatformat }}</span>
                                  </div>
                                </div>
                              </div>
                              <div class="product-info-stock-sku m-0">
                                <div>
                                  <label>Quantity: </label>
                                  <span class="info-deta">{{ item.quantity }}</span>
                                </div>
                              </div>
                            </div>
                          </td>
                        </tr>
                        {% endfor %}

                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="complete-order-detail commun-table mb-30">
                  <div class="table-responsive">
                    <table class="table">
                      <tbody>

                        <tr>
                          <td><b>Order Places :</b></td>
                          <td>{{object.updated}}</td>
                        </tr>
                        <tr>
                          <td><b>Total :</b></td>
                          <td><div class="price-box"> <span class="price">{{object.total}}</span> </div></td>
                        </tr>
                        <tr>
                          <td><b>Payment :</b></td>
                          <td>PayPal</td>
                        </tr>
                        <tr>
                          <td><b>Order No. :</b></td>
                          <td>{{object.order_id}}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="mb-30">
                  <div class="heading-part">
                    <h3 class="sub-heading">Order Confirmation</h3>
                  </div>
                  <hr>
                  <p class="mt-20">Quisque id fermentum tellus. Donec fringilla mauris nec ligula maximus sodales. Donec ac felis nunc. Fusce placerat volutpat risus, ac fermentum ex tempus eget.</p>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="print-btn">
                    <button onclick="printDiv('form-print')" class="btn btn-color" type="button">Print</button>
                    <div class="right-side float-none-xs mt-sm-30">
                      <a class="btn btn-black" href="{% url 'Products:product_list' %}">
                        <span><i class="fa fa-angle-left"></i></span>Continue Shopping
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="cart-total-table address-box commun-table mb-30">
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th>Shipping Address</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>
                          <ul>
                            <li class="inner-heading"> <b>{{ object.shipping_address.get_full_name }}</b> </li>
                            <li>
                               {{ object.shipping_address.get_address|slice:":30" }}
                            </li>
                            <li>
                               {{ object.shipping_address.get_address|slice:"30:60" }}
                            </li>
                            <li>
                               {{ object.shipping_address.get_address|slice:"60:90" }}
                            </li>
                          </ul>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="cart-total-table address-box commun-table">
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th>Billing Address</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>
                          <ul>
                            <li class="inner-heading"> <b>{{ object.billing_address.get_full_name }}</b> </li>
                               <li>
                               {{ object.billing_address.get_address|slice:":30" }}
                            </li>
                            <li>
                               {{ object.billing_address.get_address|slice:"30:60" }}
                            </li>
                            <li>
                               {{ object.billing_address.get_address|slice:"60:90" }}
                            </li>
                          </ul>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

billing/templates/payment/process.html
{% extends "base.html" %}


{% block title %}<h1> "Pay using PayPal" </h1>{% endblock %}

{% block content %}
<div class="banner inner-banner1 ">
  <div class="container">
    <section class="banner-detail center-xs">
      <h1 class="banner-title">Checkout</h1>
      <div class="bread-crumb right-side float-none-xs">
        <ul>
          <li><a href="index.html">Home</a>/</li>
          <li><a href="cart.html">Cart</a>/</li>
          <li><span>Checkout</span></li>
        </ul>
      </div>
    </section>
  </div>
</div>

<section class="checkout-section ptb-70">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="checkout-step mb-40">
          <ul>
            <li>
                <a href="{% url 'address' %}">
                <div class="step">
                  <div class="line"></div>
                  <div class="circle">1</div>
                </div>
                <span>Shipping</span>
              </a>
            </li>
            <li >
              <a href="{% url 'order:overview' %}">
                <div class="step">
                  <div class="line"></div>
                  <div class="circle">2</div>
                </div>
                <span>Order Overview</span>
              </a>
            </li>
            <li class="active">
              <a href="{% url 'payment:process' %}">
                <div class="step">
                  <div class="line"></div>
                  <div class="circle">3</div>
                </div>
                <span>Payment</span>
              </a>
            </li>
            <li >
              <a href="#">
                <div class="step">
                  <div class="line"></div>
                  <div class="circle">4</div>
                </div>
                <span>Order Complete</span>
              </a>
            </li>
            <li>
              <div class="step">
                <div class="line"></div>
              </div>
            </li>
          </ul>
          <hr>
        </div>
        <div class="checkout-content">
          <div class="row">
            <div class="col-12">
              <div class="heading-part align-center">
                <h2 class="heading">Select a payment method</h2>
              </div>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col-xl-6 col-lg-12 col-md-8 ">
              <div class="payment-option-box mb-30 align-center">

                    <div class="radio-box  align-center" >
                      <h2>PayPal</h2>
                    </div>

                    {{ form.render }}

              </div>
              <div class="payment-option-box mb-30 align-center">

                      <label for="cash">Would you like to pay by Cash on Delivery?</label>

                  <p>Vestibulum semper accumsan nisi, at blandit tortor maxi'mus in phasellus malesuada sodales odio, at dapibus libero malesuada quis.</p>

              <div class="float-none-xs"> <a class="btn btn-color" href="order-complete.html">Place Order<span><i class="fa fa-angle-right"></i></span></a> </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>
    <h1> Pay using PayPal</h1>
    {{ form.render }}

{% endblock %}