accounts/urls.py
from django.conf.urls import url
from . import views as accounts_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(redirect_authenticated_user=True,template_name='login.html'), name='login'),
    url(r'^signup/', accounts_views.signup, name='signup'),
	url(r'^myaccount/$', accounts_views.account_view, name='my_account'),
    url(r'^myaccount/account/$', accounts_views.user_address_update,name='account'),
    url(r'^myaccount/order_details/$', accounts_views.account_view, name='order_details'),
    url(r'^myaccount/password_change/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
    name='password_change'),
 	url(r'^settings/password/done/$',
    auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
    name='password_change_done'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='Logout'),
    url(r'^reset/$', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt'), name='password_reset'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html'),
        name='password_reset_complete'),
]

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_home, name='cart'),
    url(r'^update/$', views.cart_update, name='update'),
    url(r'^add/$', views.cart_add, name='add'),
    url(r'^cart/$', views.cart_remove, name='delate'),
    url(r'^wishlist/$', views.wishlist, name='wishlist'),

]

stylelure/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from shop import views
from accounts import views as accounts_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from addresses.views import checkout_address_create_view,address_update
from orders.views import overview
# from cart.views import checkout_home
from coupons.views import coupon_apply


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^account/',include('accounts.urls',namespace='accounts')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^contact/$', views.emailView, name='contact'),
    url(r'^address/$', address_update, name='address'),
    url(r'^address/add$', checkout_address_create_view, name='add_address'),
    url(r'^order/',include('orders.urls',namespace='order')),
    #url(r'^order/overview$', checkout_home, name='overview'),
    url(r'^apply/$',coupon_apply, name='apply'),
    url(r'^payment/',include('billing.urls',namespace='payment')),
    url(r'^contact/success$', views.successView, name='success'),
    url(r'^product/',include('Products.urls',namespace='Products')),
    url(r'^search/',include('search.urls',namespace='search')),
    # url(r'^review/', include('review.urls')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^wishlist/',include('wishlist.urls',namespace='wishlist')),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, get_user_model
from localflavor.in_.forms import INStateSelect,INStateField,INAadhaarNumberField,INZipCodeField
from django_countries.fields import CountryField

User = get_user_model()


class SignUpForm(UserCreationForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    first_name = forms.CharField(max_length=10, label='First Name')
    last_name = forms.CharField(max_length=10, label='Last Name')
    phone_number = forms.RegexField(
        regex='^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[6-9]\d{9}$')
    email = forms.CharField(max_length=254, required=True,
                            widget=forms.EmailInput())
    date_of_birth = forms.DateField(widget=forms.DateInput(
        attrs={'type': 'date'}), label='Date of Birth')
    CHOICES = [('M', 'Male'), ('F', 'Female')]
    gender = forms.ChoiceField(choices=CHOICES, widget=forms.Select(
        attrs={"name": "select_0", "class": "form-control"}), required=True)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput,
                help_text="""• Your password cant be too similar to your other personal information.
                            <br/>• Your password must contain at least 8 characters.
                            <br/>• Your password can't be a commonly used password.
                             <br/>• Your password can't be entirely numeric""")
    password2 = forms.CharField(label='Password confirmation',
                                widget=forms.PasswordInput,
                                help_text='• Enter the same password as before, for verification.')
    receive_newsletter = forms.BooleanField(
        required=False, label=('  Sign Up for Newsletter'), initial=True)

    class Meta:
        model = User
        # unique_together = ('email',)
        fields = ['first_name', 'last_name', 'phone_number', 'email',
                  'gender', 'date_of_birth', 'password1', 'password2']


# 
# class AddressForm(forms.ModelForm):
#     """docstring for AddressForm"""
#     phone_number = forms.RegexField(
#         regex='^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[6-9]\d{9}$')
#     state=INStateField(widget=INStateSelect())
#     street_address_1=forms.CharField(widget=forms.Textarea(
#             attrs={'rows': 3}),max_length=100, help_text='Please provide the number and street.')
#     street_address_2=forms.CharField(widget=forms.Textarea(
#             attrs={'rows': 1}),max_length=100, help_text='Please include landmark'
#         '(e.g : Opposite Bank) as the carrier service may find it easier to locate your address.')
#     # aadhaar=INAadhaarNumberField()
#     postal_code=INZipCodeField()
#     # country=CountryField()
#
#     class Meta:
#         model= User
#         fields=['first_name', 'last_name', 'phone_number', 'email',
#                 'street_address_1','street_address_2','country','state','postal_code'
#                   ]


        # def __init__(self, *args, **kw):
        #     super(AddressForm, self).__init__(*args, **kw)


    # class Meta:
    #     model = User
    #     fields = ('full_name', 'email',) #'full_name',)

    # def clean_password2(self):
    #     # Check that the two password entries match
    #     password1 = self.cleaned_data.get("password1")
    #     password2 = self.cleaned_data.get("password2")
    #     if password1 and password2 and password1 != password2:
    #         raise forms.ValidationError("Passwords don't match")
    #     return password2

    # def save(self, commit=True):
    #     # Save the provided password in hashed format
    #     user = super(RegisterForm, self).save(commit=False)
    #     user.set_password(self.cleaned_data["password1"])
    #     user.is_active = False # send confirmation email via signals
    #     # obj = EmailActivation.objects.create(user=user)
    #     # obj.send_activation_email()
    #     if commit:
    #         user.save()
    #     return user

# class SignUpForm(UserCreationForm):
#     first=forms.CharField(max_length=10,label='First Name')
#     last=forms.CharField(max_length=10,label='Last Name')
#     phone= forms.RegexField(regex='^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[6-9]\d{9}$')
#     email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
#     date=forms.DateField(widget=forms.DateInput(attrs={'type':'date'}),label='Date of Birth')
#     CHOICES=[('m','Male'),('f','Female')]
#     gender = forms.ChoiceField(choices=CHOICES, widget=forms.Select(attrs={"name": "select_0","class": "form-control"}),required=True)
#     receive_newsletter = forms.BooleanField(required=False,label=('  Sign Up for Newsletter'),initial=True)


#     class Meta:
#         model = User
#         unique_together = ('email',)
#         fields = ('first','last','phone','email','date','gender', 'password1', 'password2')


class GuestForm(forms.Form):
    email    = forms.EmailField()

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model,login as auth_login
from .forms import SignUpForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
from cart.models import Cart
from billing.models import BillingProfile
from orders.models import Order
from django.contrib.auth.forms import PasswordChangeForm
from addresses.forms import AddressForm
from addresses.models import Address

# from .models import UserProfile

User = get_user_model()

def signup(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        if request.method == 'POST':
            form = SignUpForm(request.POST)

            if form.is_valid():
                user = form.save()
                auth_login(request, user,backend='django.contrib.auth.backends.ModelBackend')
                return redirect('index')
        else:
            form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def account_view(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
    # form = PasswordChangeForm(request.user)
    return render(request,'my_account.html',{'object':order_obj,'billing_profile':billing_profile})


# class Account_View(UpdateView):

#     template_name = 'my_account.html'
#     form_class = PasswordChangeForm(request.user)
#     second_form_class = AddressForm
#     success_url = reverse_lazy('success')

#     def get_context_data(self, **kwargs):
#         context = super(MyView, self).get_context_data(**kwargs)
#         if 'form' not in context:
#             context['form'] = self.form_class(initial={'user': request.user})
#         if 'form2' not in context:
#             context['form2'] = self.second_form_class()
#         return context

#     def get_object(self):
#         return get_object_or_404(Model, pk=self.request.session['someval'])

#     def form_invalid(self, **kwargs):
#         return self.render_to_response(self.get_context_data(**kwargs))

#     def post(self, request, *args, **kwargs):

#         # get the user instance
#         self.object = self.get_object()

#         if 'form' in request.POST:

#             # get the primary form
#             form_class = self.get_form_class()
#             form_name = 'form'

#         else:

#             # get the secondary form
#             form_class = self.second_form_class
#             form_name = 'form2'

#         # get the form
#         form = self.get_form(form_class)

#         # validate
#         if form.is_valid():
#             return self.form_valid(form)
#         else:
#             return self.form_invalid(**{form_name: form})

# @method_decorator(login_required, name='dispatch')
# class UserUpdateView(UpdateView):
#     model = Address
#     # fields['email'].widget.attrs['readonly'] = True
#     # fields = ('first_name', 'last_name', 'email','country' )
#     form_class = AddressForm

#     # form_class.fields['email'].widget.attrs['readonly'] = True
#     template_name = 'account-details.html'
#     success_url = reverse_lazy('account')

#     def get_object(self):
#         return self.request.user

#     def get_initial(self):
#         return { 'country': 'india', 'state':'Gujarat' }

def user_address_update(request):   
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    print(billing_profile)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated():
            address_qs = Address.objects.filter(billing_profile=billing_profile) 
        try:
            shipping_address = Address.objects.get(billing_profile=billing_profile.id,address_type='shipping')
        except Address.DoesNotExist:
            print("Show message to user, Address is gone?")
            return redirect("cart:cart")
        try:   
            billing_address = Address.objects.get(billing_profile=billing_profile.id,address_type='billing') 
        except Address.DoesNotExist:
            print(" Address is gone?")
            return redirect("cart:cart")
        # shipping_address = Address.objects.get(id=27)
        # import pdb; pdb.set_trace()
        form1=AddressForm(prefix='form1',instance=shipping_address,data=request.POST or None )
        form2=AddressForm(prefix='form2',instance=billing_address,data=request.POST or None)

        if request.method=='POST':
            import pdb; pdb.set_trace()
            if form2.is_valid():
                form2.save()
            if form1.is_valid():
                form1.save()
                

    
    return render(request,'account-details.html',{'form1':form1,'form2':form2})  

accounts/templates/account-details.html
{% extends 'my_account.html' %}
{% block my_account_content %}
<div class="col-lg-3">
          <div class="account-sidebar account-tab mb-sm-30">
            <div class="dark-bg tab-title-bg">
              <div class="heading-part">
                <div class="sub-title"><span></span> My Account</div>
              </div>
            </div>
            <div class="account-tab-inner">
              <ul class="account-tab-stap">
                <li id="step1" > <a href="{% url 'accounts:my_account' %}">My Dashboard<i class="fa fa-angle-right"></i> </a> </li>
                <li id="step2" class="active"> <a href="{% url 'accounts:account' %}">Account Details<i class="fa fa-angle-right"></i> </a> </li>
                <li id="step3"> <a href="javascript:void(0)">My Order List<i class="fa fa-angle-right"></i> </a> </li>
                <li id="step4" > <a href="{% url 'accounts:password_change' %}">Change Password<i class="fa fa-angle-right"></i> </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-9">
          <div id="data-step2" class="account-content" >
            <div class="row">
              <div class="col-12">
                <form class="main-form full">
              <div class="row">
              </div>
            </form>
                <div class="heading-part heading-bg mb-30">
                  <h2 class="heading ma-0">Account Details</h2>
                </div>
              </div>
            </div>
            <div class="m-0">
              <form  method="post" class="main-form full">
                {% csrf_token %}
                <div class="mb-20">
                  <div class="row">
                    <div class="col-12 mb-20">
                      <div class="heading-part">
                        <h3 class="sub-heading">Shipping Address</h3>
                      </div>
                      <hr>
                    </div>
                    {% include 'includes/aad_form.html' with form=form1 %}
            
                  </div>
                </div>
                 <div class="mb-20">
                  <div class="row">
                    <div class="col-12 mb-20">
                      <div class="heading-part">
                        <h3 class="sub-heading">Billing Address</h3>
                      </div>
                      <hr>
                    </div>
                    {% include 'includes/aad_form.html' with form=form1 %}
            
                  </div>
                </div>

                 <button type="submit" class="btn-left">Save</button>
              </form>
            </div>
          </div>
        </div>
          {% endblock %}

accounts/templates/login.html
{% extends 'base_account.html' %}

{% block account_content %}
<div class="login-form">
    <div class="container">
        <h2>CUSTOMER LOGIN</h2>
        <div class="row">
            <div class="col-md-6">
                <div class="customer-login">
                    <h3>Registered Customers</h3>
                    <p>if you have an account sign with your email address.</p>
                    <form method="post" novalidate>
                        {% csrf_token %}           
                        {% include 'includes/form.html' %}
                       <button type="submit" class="btn-left">SIGN IN</button> <a href="{% url 'accounts:password_reset' %}"> Forgot Your Password?</a>
                    </form>                             
                    <div class="field">* Required Fields</div>
                </div>
            </div>
              <div class="col-md-6">
                            <div class="new-customers">
                                <h3>Login</h3>
                                <div class="row mt-5 mb-5" align='center' onloadedmetadata="">
                                <a href="{% url 'social:begin' 'google-oauth2' %}"><button type="submit" class="google btn-left ">
                                  <i class="fa fa-google-plus" aria-hidden="true"></i> | Sign in with Google+</button></a>
                              </div>
                              <div class="row" align='center' onloadedmetadata="">
                             <a href="{% url 'social:begin' 'google-oauth2' %}"><button type="submit" class="github btn-left ">
                               <i class="fa fa-github" aria-hidden="true"></i> | Sign in with GitHub</button></a>
                           </div>
                            </div>
                    </div>
            <div class="col-md-12" align="center" >
                <div class="new-customers">
                    <form action="{% url 'accounts:signup' %}">
                    <h3>New Customers</h3>
                    <p>Creating an account has many benefits: check out faster, keep more than one address, track orders and more.</p>
                    <button type="submit" class="btn-left">Create an Account</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/my_account.html
{% extends 'base_account.html' %}
{% load static %}
{% block account_content %}

  <div class="banner inner-banner1 ">
    <div class="container">
      <section class="banner-detail center-xs">
        <h1 class="banner-title">Account</h1>
        <div class="bread-crumb right-side float-none-xs">
          <ul>
            <li><a href="{% url 'index' %}">Home</a>/</li>
            <li><span>Account</span></li>
          </ul>
        </div>
      </section>
    </div>
  </div>


  <section class="checkout-section ptb-70">
    <div class="container">
      <div class="row">
        {% block my_account_content %}
        <div class="col-lg-3">
          <div class="account-sidebar account-tab mb-sm-30">
            <div class="dark-bg tab-title-bg">
              <div class="heading-part">
                <div class="sub-title"><span></span> My Account</div>
              </div>
            </div>
            <div class="account-tab-inner">
              <ul class="account-tab-stap">
                <li id="step1" class="active"> <a href="{% url 'accounts:my_account' %}">My Dashboard<i class="fa fa-angle-right"></i> </a> </li>
                <li id="step2"> <a href="{% url 'accounts:account' %}">Account Details<i class="fa fa-angle-right"></i> </a> </li>
                <li id="step3"> <a href="javascript:void(0)">My Order List<i class="fa fa-angle-right"></i> </a> </li>
                <li id="step4"> <a href="{% url 'accounts:password_change' %}">Change Password<i class="fa fa-angle-right"></i> </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-9">
          
          <div id="data-step1" class="account-content" >
            <div class="row">
              <div class="col-12">
                <div class="heading-part heading-bg mb-30">
                  <h2 class="heading ma-0">Account Dashboard</h2>
                </div>
              </div>
            </div>
      
            <div class="mb-30">
              <div class="row">
                <div class="col-12">
                  <div class="heading-part">
                    <h3 class="sub-heading">Hello {{ object.shipping_address.get_full_name }}</h3>
                  </div>
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec eros tellus, scelerisque nec, rhoncus eget, laoreet sit amet.<a class="account-link" id="subscribelink" href="#">Click Here</a></p>
                </div>
              </div>
            </div>
            <div class="m-0">
              <div class="row">
                <div class="col-12 mb-20">
                  <div class="heading-part">
                    <h3 class="sub-heading">Account Information</h3>
                  </div>
                  <hr>
                </div>
                <div class="col-md-6">
                  <div class="cart-total-table address-box commun-table">
                    <div class="table-responsive">
                      <table class="table">
                        <thead>
                          <tr>
                            <th>Shipping Address</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td><ul>
                                <li class="inner-heading"> <b>{{ object.shipping_address.get_full_name }}</b> </li>
                                <li>
                                   {{ object.shipping_address.get_address|slice:":30" }}
                                </li>
                                <li>
                                   {{ object.shipping_address.get_address|slice:"30:60" }}
                                </li>
                                <li>
                                   {{ object.shipping_address.get_address|slice:"60:90" }}
                                </li>
                              </ul></td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="cart-total-table address-box commun-table">
                    <div class="table-responsive">
                      <table class="table">
                        <thead>
                          <tr>
                            <th>Billing Address</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>
                              <ul>
                                <li class="inner-heading"> <b>{{ object.billing_address.get_full_name }}</b> </li>
                                <li>
                                {{ object.billing_address.get_address|slice:":30" }}
                             </li>
                             <li>
                                {{ object.billing_address.get_address|slice:"30:60" }}
                             </li>
                             <li>
                                {{ object.billing_address.get_address|slice:"60:90" }}
                             </li>
                              </ul>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
         
        </div>
         {% endblock %}
      </div>
    </div>
  </section>


{% endblock %}

   <div class="col-12">
                  <div class="input-box">
                    <label for="old-pass">Old-Password</label>
                    <input type="password" placeholder="Old Password" required id="old-pass">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="input-box">
                    <label for="login-pass">Password</label>
                    <input type="password" placeholder="Enter your Password" required id="login-pass">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="input-box">
                    <label for="re-enter-pass">Re-enter Password</label>
                    <input type="password" placeholder="Re-enter your Password" required id="re-enter-pass">
                  </div>
                </div>
                <div class="col-12">
                  <button class="btn-color btn-left" type="submit" name="submit">Change Password</button>
                </div>

accounts/templates/password_change.html
{% extends 'my_account.html' %}
{% block my_account_content %}
<div class="col-lg-3">
          <div class="account-sidebar account-tab mb-sm-30">
            <div class="dark-bg tab-title-bg">
              <div class="heading-part">
                <div class="sub-title"><span></span> My Account</div>
              </div>
            </div>
            <div class="account-tab-inner">
              <ul class="account-tab-stap">
                <li id="step1" > <a href="{% url 'accounts:my_account' %}">My Dashboard<i class="fa fa-angle-right"></i> </a> </li>
                <li id="step2"> <a href="{% url 'accounts:account' %}">Account Details<i class="fa fa-angle-right"></i> </a> </li>
                <li id="step3"> <a href="javascript:void(0)">My Order List<i class="fa fa-angle-right"></i> </a> </li>
                <li id="step4" class="active"> <a href="{% url 'accounts:password_change' %}">Change Password<i class="fa fa-angle-right"></i> </a> </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-9">
    <div id="data-step4" class="account-content" >
            <div class="row">
              <div class="col-12">
                <div class="heading-part heading-bg mb-30">
                  <h2 class="heading m-0">Change Password</h2>
                </div>
              </div>
            </div>
            <form class="main-form full" novalidate>
              <div class="row">
             {% include 'includes/form.html' %}
              </div>
              <button type="submit" class="btn-left">Change Password</button>
            </form>
          </div>
        </div>
    {% endblock %}

accounts/templates/password_reset.html
{% extends 'base_account.html' %}
{% block account_content %}
<div class="login-form">
    <div class="container">
    <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
    </div>
</div>
{% endblock %}

accounts/templates/password_reset_complete.html
{% extends 'base_account.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/password_reset_confirm.html
{% extends 'base_account.html' %}

{% block title %}
  {% if validlink %}
    Change password 
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password </h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/password_reset_done.html
{% extends 'base_account.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}


If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Django Boards Team