Products/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^product_list/', views.product_list_view, name='product_list_view'),
    url(r'^product_list/(?P<category_slug>[-\w]+)/$', views.product_list_view, name='product_list_view_by_category'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    
    
]

billing/urls.py
from django.conf.urls import url
from django.utils.translation import gettext_lazy as _
from . import views


urlpatterns = [
    url(_(r'^process/$'), views.payment_process, name='process'),
    url(_(r'^done/$'), views.payment_done, name='done'),
    url(_(r'^canceled/$'), views.payment_canceled, name='canceled'),
]

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_home, name='cart'),
    url(r'^update/$', views.cart_update, name='update'),
    url(r'^add/$', views.cart_add, name='add'),
    url(r'^cart/$', views.cart_remove, name='delate'),
    url(r'^wishlist/$', views.wishlist, name='wishlist'),

]

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.overview, name='overview'),
  
]

stylelure/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from shop import views
from accounts import views as accounts_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from addresses.views import checkout_address_create_view,address_update
from orders.views import overview
# from cart.views import checkout_home
from coupons.views import coupon_apply


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^account/',include('accounts.urls',namespace='accounts')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^contact/$', views.emailView, name='contact'),
    url(r'^address/$', address_update, name='address'),
    url(r'^address/add$', checkout_address_create_view, name='add_address'),
    url(r'^order/',include('orders.urls',namespace='order')),
    #url(r'^order/overview$', checkout_home, name='overview'),
    url(r'^apply/$',coupon_apply, name='apply'),
    url(r'^payment/',include('billing.urls',namespace='payment')),
    url(r'^contact/success$', views.successView, name='success'),
    url(r'^product/',include('Products.urls',namespace='Products')),
    url(r'^search/',include('search.urls',namespace='search')),
    # url(r'^review/', include('review.urls')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^wishlist/',include('wishlist.urls',namespace='wishlist')),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from decimal import Decimal
from django.db import models
from django.conf import settings
from Products.models import Product
from django.db.models.signals import pre_save, post_save, m2m_changed,post_delete
from colorfield.fields import ColorField
from datetime import datetime

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        user = request.user
        #cart_id = request.session.get("cart_id", None)
        if request.user.id == None:
            user=None
        qs = Cart.objects.filter(user=user)
        # cart_id = request.session.get("cart_id", None)
        # asp = Cart.objects.filter(id=cart_id)
        if qs.count() > 0:
            new_obj = False
            cart_obj = qs.first()
            print(cart_obj)
            request.session['cart_id'] = cart_obj.id

            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        # elif asp.count() == 1:
        #     new_obj = False
        #     cart_obj = qs.first()
        #     print(cart_obj)
        #     request.session['cart_id'] = cart_obj.id
        #     if request.user.is_authenticated() and cart_obj.user is None:
        #         cart_obj.user = request.user
        #         cart_obj.save()
        # # cart_id = request.session.get("cart_id", None)
        # qs = self.get_queryset().filter(id=cart_id)
        # print(cart_id,'qs',qs)
        # if qs.count() == 1:
        #     new_obj = False
        #     cart_obj = qs.first()
        #     if request.user.is_authenticated() and cart_obj.user is None:
        #         cart_obj.user = request.user
        #         cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj
    # def new_or_get(self, request):
    #     cart_id = request.session.get("cart_id", None)
    #     qs = self.get_queryset().filter(id=cart_id)
    #     if qs.count() == 1:
    #         new_obj = False
    #         cart_obj = qs.first()
    #         if request.user.is_authenticated() and cart_obj.user is None:
    #             cart_obj.user = request.user
    #             cart_obj.save()
    #     else:
    #         cart_obj = Cart.objects.new(user=request.user)
    #         new_obj = True
    #         request.session['cart_id'] = cart_obj.id
    #     return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)

    # product_list=[]
    # def item_list(self,id):
    #     item_count = Cart.objects.filter(id=4).first().items.all().count()
    #     for i in range(item_count):
    #         product_list.append(Cart.objects.filter(id=4).first().items.all()[i].product_id)
    #     return product_list


class Cart(models.Model):
    user           = models.ForeignKey(User, null=True, blank=True)
    #products      = models.ManyToManyField(Product, blank=True)
    subtotal       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total          = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated        = models.DateTimeField(auto_now=True)
    created_date   = models.DateTimeField(auto_now_add=True)
    count          = models.PositiveIntegerField(default=0)


    objects = CartManager()

    def __str__(self):
        return str(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())



class CartItem(models.Model):
    product = models.ForeignKey(Product,related_name='products',on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,related_name='items',null=True,on_delete=models.CASCADE)
    selected_color = ColorField(default=None)
    quantity = models.PositiveIntegerField(default=1)
    selected_size  = models.CharField(max_length=30)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.product.discounted_price * self.quantity

    # def save(self, *args, **kwargs):
    #     self.cart.subtotal += self.quantity * self.product.discounted_price
    #     self.cart.count += self.quantity
    #     self.cart.updated = datetime.now()
    #     self.cart.save()
    #     # import pdb; pdb.set_trace()
    #     super(CartItem, self).save(*args, **kwargs)

    # def delete(self, *args, **kwargs):
    #     self.cart.subtotal += self.quantity * self.product.discounted_price
    #     self.cart.count += self.quantity
    #     self.cart.updated = datetime.now()
    #     self.cart.save()
    #     import pdb; pdb.set_trace()
    #     super(CartItem, self).save(*args, **kwargs)

# def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
#     if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
#         products = instance.products.all()
#         total = 0
#         for x in products:
#             total += x.price
#         if instance.subtotal != total:
#             instance.subtotal = total
#             instance.save()

# m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08)
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

# def pre_save_cart_item_receiver(sender, instance, *args, **kwargs):
#     qs = CartItem.objects.get(cart=instance.cart,
#                product=instance.product,selected_color=instance.selected_color,
#                selected_size=instance.selected_size)
#     if qs:
#         qs.quantity += 1
#         qs.save()
#         return


# pre_save.connect(pre_save_cart_item_receiver, sender=CartItem)

def post_delete_cart_item_receiver(sender, instance, using,**kwargs):
    line_cost = instance.quantity * instance.product.discounted_price
    instance.cart.subtotal -= line_cost
    instance.cart.count -= instance.quantity
    instance.cart.updated = datetime.now()
    instance.cart.save()

post_delete.connect(post_delete_cart_item_receiver, sender=CartItem)


def post_save_update_cart(sender, instance,created,*args, **kwargs):
    if created:
        line_cost = instance.quantity * instance.product.discounted_price
        instance.cart.subtotal += line_cost
        instance.cart.count += instance.quantity
        instance.cart.updated = datetime.now()
        instance.cart.save()
        print(instance.cart.subtotal)
        # import pdb; pdb.set_trace()
post_save.connect(post_save_update_cart, sender=CartItem)

coupons/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class CouponApplyForm(forms.Form):
    code = forms.CharField(label=_('Coupon'))

cart/views.py
from django.shortcuts import render,redirect
from .models import Cart,CartItem
from Products.models import Product

from orders.models import Order
from coupons.forms import CouponApplyForm

def wishlist(request):
    return render(request,'cart/wishlist.html')

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    print(request.session.get('cart_id'))
    tax= cart_obj.total - cart_obj.subtotal

    return render(request,'cart/cart.html',{"cart": cart_obj,'tax':tax})

def cart_add(request):
   # cart_obj, new_obj = Cart.objects.new_or_get(request)
   # print(cart_obj)
    product_id = request.POST.get('product_id')
    selected_color = request.POST.get('selected_color')
    selected_size = request.POST.get('selected_size')
   # print(selected_color)
  # selected_color=rgb2hex(selected_color[0],selected_color[1],selected_color[2])
    #print(selected_size)
    # total=cart_obj.get_total_cost
    # print(total)
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user, product is gone?")
            return redirect("cart:cart")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        #print('a',Cart.items.all())

        try:
            qs = CartItem.objects.get(cart=cart_obj,
                product=product_id,selected_color=selected_color,
                selected_size=selected_size)
            qs.quantity += 1
            qs.cart.subtotal+=qs.product.discounted_price
            qs.cart.count+=1
            qs.cart.save()
            qs.save()

        except CartItem.DoesNotExist:
            CartItem.objects.create(product=product_obj,cart=cart_obj,
            selected_color=selected_color,selected_size=selected_size)
        cart_id = request.session.get('cart_id')
        #print('a',item_list(id=cart_id))
        # print(product_id)
        # import pdb; pdb.set_trace()
        # if product_id in item_list(id=cart_id):
        #     CartItem.objects.get(product_obj)
        # else:
        # except
        # return redirect(product_obj.get_absolute_url())
    return redirect("cart:cart")


def cart_update(request):
    product_id = request.POST.get('product_id')
    cart_item_id = request.POST.get('cart_item_id')
    cart_id = request.session.get('cart_id')
    quantity = request.POST.get('quantity')

    if product_id in item_list(id=cart_id):
        qs = CartItem.objects.get(id=cart_item_id)
        qs.quantity=quantity
        qs.cart.subtotal+=qs.product.discounted_price
        qs.cart.count+=1
        qs.cart.save()   
        qs.save()
    else:
        pass
    return redirect('cart:cart')





def cart_remove(request):
    product_id = request.POST.get('product_id')
    cart_item_id = request.POST.get('cart_item_id')
    cart_id = request.session.get('cart_id')
    # print('as',cart_id)
    # print(product_id)
    # import pdb; pdb.set_trace()
    if product_id in item_list(id=cart_id):
        CartItem.objects.filter(id=cart_item_id).all().delete()
    return redirect('cart:cart')

product_list=[]
def item_list(id):
    item_count = Cart.objects.filter(id=id).first().items.all().count()
    for i in range(item_count):
        product_=str(Cart.objects.filter(id=id).first().items.all()[i].product_id)
        product_list.append(product_)
    return product_list


# def rgb2hex(r,g,b):
#     return "#{:02x}{:02x}{:02x}".format(r,g,b)

# def checkout_home(request):
#     cart_obj, cart_created = Cart.objects.new_or_get(request)
#     order_obj = None
#     if cart_created or cart_obj.items.count() == 0:
#         return redirect("cart:cart")

#     guest_form = GuestForm()
#     coupon_apply_form = CouponApplyForm()

#     billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
#     print(billing_profile)
#     address_qs = None
#     if billing_profile is not None:
#         if request.user.is_authenticated():
#             address_qs = Address.objects.filter(billing_profile=billing_profile)
#         order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
#         try:
#             order_obj.shipping_address = Address.objects.get(billing_profile=billing_profile.id,address_type='shipping')
#         except Address.DoesNotExist:
#             print("Show message to user, Address is gone?")
#             return redirect("cart:cart")
#         try:
#             order_obj.billing_address = Address.objects.get(billing_profile=billing_profile.id,address_type='billing')
#         except Address.DoesNotExist:
#             print(" Address is gone?")
#             return redirect("cart:cart")
#         if order_obj.billing_address or order_obj.shipping_address:
#             order_obj.save()


#     # print(order_obj.billing_address)
#     context = {
#         'form':coupon_apply_form,
#         "object": order_obj,
#         "billing_profile": billing_profile,
#         "guest_form": guest_form,
#         "address_qs": address_qs,
#     }
#     return render(request, "order_overview.html", context)

templates/Contact.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="contact-us">
    <div class="container">
        <h2>Contact Us</h2>
        <div class="row">
            <div class="col-sm-8">
            	 <form method="post" novalidate>
                        {% csrf_token %}
                        {% include 'includes/contact_form.html' %}
                      <button type="submit" class="btn-left">SEND</button>
                    <div class="field">* Required Fields</div>
                    </form>
            </div>
            <div class="col-sm-4">
                <div class="side-bar">
                    <div class="cright-side">
                        <div class="name">
                            <div class="icon">
                                <i class="pe-7s-global"></i>
                            </div>
                            <div class="info">
                                <h4>ADDRESS</h4>
                                <P>Sola Rd, Thaltej, Ahmedabad, Gujarat 380059</P>
                            </div>
                        </div>

                    </div>
                    <div class="cright-side">
                        <div class="name">
                            <div class="icon">
                                <i class="fa fa-envelope-o"></i>
                            </div>
                            <div class="info">
                                <h4>E-Mail</h4>
                                <P>support@stylelure.com info@stylelure.com</p>
                            </div>
                        </div>
                    </div>
                    <div class="cright-side">
                        <div class="name">
                            <div class="icon">
                                <i class="fa fa-phone"></i>
                            </div>
                            <div class="info">
                                <h4>PHONE</h4>
                                <P>+49 07072 88 65 75
                                    <br>+49 06224 19 40 08</P>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="google-map">
    <img src="{% static "images/map2.png" %}" atl="responcive">
</div>

{% endblock content%}

templates/base_product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% block  bread-crumb-block %}
<div class="banner inner-banner1 ">
  <div class="container">
    <section class="banner-detail center-xs">
      <h1 class="banner-title">{% if category == None %} Women {% else %}{{category}} {%endif%}</h1>
      <div class="bread-crumb right-side float-none-xs">
        <ul>
          <li><a href="{% url 'index' %}">Home</a>/</li>
          <li><span>{% if category == None %} Women {% else %}{{category}} {%endif%}</span></li>
        </ul>
      </div>
    </section>
  </div>
</div>
{% endblock %}

<section class="ptb-70">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 mb-sm-30">
        <div class="sidebar-block">
          <div class="sidebar-box listing-box mb-40"> <span class="opener plus"></span>
            <div class="sidebar-title">
              <h3><span>Categories</span></h3>
            </div>
            <div class="sidebar-contant">
              <ul>
              {% for category in categories %}
              <li><a href="{{category.get_absolute_url }}">{{category.Category_name}}<span></span></a></li>
              {% endfor %}

              </ul>
            </div>
          </div>
          <div class="sidebar-box mb-40"> <span class="opener plus"></span>
            <div class="sidebar-title">
              <h3><span>Shop by</span></h3>
            </div>
            <div class="sidebar-contant">
              <div class="price-range mb-30">
                <div class="inner-title">Price range</div>
                <input class="price-txt" type="text" id="amount">
                <div id="slider-range"></div>
              </div>


              <div class="mb-20">

              </div>
              <form method='POST' action='{% url "Products:product_list" %}' class="form" id="price_refine"> {% csrf_token %}
                <input type='hidden' name='product_id' value='{{ object.id }}' />
                <input type='hidden' id='max_price' name='selected_color' value="" />
                <input type='hidden' id='min_price' name='selected_size' value="" />  
               <button type='submit'  class='btn btn-left btn-success'>Refine</button>
              </form>
               </div>
            </div>

          </div>
        </div>
        <div class="col-lg-9">
          <div class="shorting mb-30">
            <div class="row">
              <div class="col-lg-6">
                <div class="view">
                  <div class="list-types grid  "> <a href="{% url 'Products:product_list' %}">
                    <div class="grid-icon list-types-icon"></div>
                  </a>
                </div>
                <div class="list-types list active"> <a href="{% url 'Products:product_list_view' %}">
                  <div class="list-icon list-types-icon"></div>
                </a>
              </div>
            </div>

          </div>
        
        </div>
      </div>
      {% block product__list %}
     



{% endblock product__list%}
</div>
</div>
</div>
</section>

{% endblock %}

templates/my_account_1.html
{% extends 'base_account.html' %}
{% block account_content %}

 <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Save changes</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/order_overview.html
{% extends 'base_account.html' %}
{% load static %}
{% block account_content %}

  <div class="banner inner-banner1 ">
    <div class="container">
      <section class="banner-detail center-xs">
        <h1 class="banner-title">Checkout</h1>
        <div class="bread-crumb right-side float-none-xs">
          <ul>
            <li><a href="index.html">Home</a>/</li>
            <li><a href="cart.html">Cart</a>/</li>
            <li><span>Checkout</span></li>
          </ul>
        </div>
      </section>
    </div>
  </div>

  <section class="checkout-section ptb-70">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="checkout-step mb-40">
            <ul>
              <li>
                  <a href="{% url 'address' %}">
                  <div class="step">
                    <div class="line"></div>
                    <div class="circle">1</div>
                  </div>
                  <span>Shipping</span>
                </a>
              </li>
              <li class="active">
                <a href="{% url 'order:overview' %}">
                  <div class="step">
                    <div class="line"></div>
                    <div class="circle">2</div>
                  </div>
                  <span>Order Overview</span>
                </a>
              </li>
              <li>
                <a href="{% url 'payment:process' %}">
                  <div class="step">
                    <div class="line"></div>
                    <div class="circle">3</div>
                  </div>
                  <span>Payment</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <div class="step">
                    <div class="line"></div>
                    <div class="circle">4</div>
                  </div>
                  <span>Order Complete</span>
                </a>
              </li>
              <li>
                <div class="step">
                  <div class="line"></div>
                </div>
              </li>
            </ul>
            <hr>
          </div>
          <div class="checkout-content">
            <div class="row">
              <div class="col-12">
                <div class="heading-part align-center">
                  <h2 class="heading">Order Overview</h2>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-8 mb-sm-30">
                <div class="cart-item-table commun-table mb-30">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Product</th>
                          <th>Product Detail</th>
                          <th>Sub Total</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for item in object.cart.items.all %}

                        <tr>
                          <td>
                            <a href="{{item.product.get_absolute_url}}">
                            <div class="product-image"><img alt="Stylelure" src="{{ item.product.images.first.image.url }}"></div>
                            </a>
                          </td>
                          <td><div class="product-title"> <a href="{{item.product.get_absolute_url}}">{{item.product.title|truncatechars:25}}</a>
                              <div class="product-info-stock-sku m-0">
                                <div>
                                  <label>Price: </label>
                                  <div class="price-box"> <span class="info-deta price">${{ item.product.discounted_price|floatformat }}</span> </div>
                                </div>
                              </div>
                              <div class="product-info-stock-sku m-0">
                                <div>
                                  <label>Quantity: </label>
                                  <span class="info-deta">{{item.quantity}}</span> </div>
                              </div>
                            </div>
                            <div class="color-btn">
                                {% if item.selected_color %}
                              <div class="btn-btn">
                                <div class="cart-main-box-color">
                                  <div class="cart-red-box" style="background-color:{{item.selected_color}}"></div>
                                </div>
                              </div>
                              {%endif%}

                              {% if item.selected_size %}
                              <div class="cart-center-btn">
                                <div class="main-box">
                                  <div class="box">{{item.selected_size}}</div>
                                </div>
                              </div>
                              {%endif%}
                            </div>
                          </td>
                          <td><div data-id="100" class="total-price price-box"> <span class="price">${{item.get_cost}}</span> </div></td>
                          <td><i class="fa fa-trash cart-remove-item" data-id="100" title="Remove Item From Cart"></i></td>
                        </tr>
                        {% endfor %}

                      </tbody>
                    </table>
                  </div>
                </div>
                <div>
              <form action="{% url "apply" %}" method="post">
                {% csrf_token %}
                {% if object.coupon != None %}
                <label for="id_code">Coupon:</label>
                <input type="text" name="code" id='coupon' value="{{ object.coupon}}">
                <input type="submit" class=" btn-left btn-success mb-5 disabled" value="Applied"></input>
                {% else %}
                {{ form }}
                <input type="submit" class="btn-left mb-5" value="Apply"></input>
                {% endif %}
              </form >
              </div>
                <div class="cart-total-table commun-table mb-30">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th colspan="2">Cart Total</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>Item(s) Subtotal</td>
                          <td><div class="price-box"> <span class="price">${{object.cart.total}}</span> </div></td>
                        </tr>
                        <tr>
                          <td>Shipping</td>
                          <td><div class="price-box"> <span class="price">$5.99</span> </div></td>
                        </tr>
                        <tr>
                          <td><b>Amount Payable</b></td>
                          <td><div class="price-box"> <span class="price"><b>${{object.get_total_price_after_discount}}</b></span> </div></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="right-side float-none-xs"> <a href="{% url 'payment:process' %}" class="btn btn-color">Next</a>
                </div>
              </div>
              <div class="col-md-4">

                {# {% for  address in %} #}
                <div class="cart-total-table address-box commun-table mb-30">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Shipping Address</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>
                            <ul>
                              <li class="inner-heading"> <b>{{ object.shipping_address.get_full_name }}</b> </li>
                              <li>
                                 {{ object.shipping_address.get_address|slice:":30" }}
                              </li>
                              <li>
                                 {{ object.shipping_address.get_address|slice:"30:60" }}
                              </li>
                              <li>
                                 {{ object.shipping_address.get_address|slice:"60:90" }}
                              </li>
                            </ul>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div class="cart-total-table address-box commun-table">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Billing Address</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>
                            <ul>
                              <li class="inner-heading"> <b>{{ object.billing_address.get_full_name }}</b> </li>
                                 <li>
                                 {{ object.billing_address.get_address|slice:":30" }}
                              </li>
                              <li>
                                 {{ object.billing_address.get_address|slice:"30:60" }}
                              </li>
                              <li>
                                 {{ object.billing_address.get_address|slice:"60:90" }}
                              </li>
                            </ul>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


{% endblock %}

templates/update-cart.html
<form method='POST' action='{% url "cart:update" %}' class="form"> {% csrf_token %}
    <input type='hidden' name='product_id' value='{{ product.id }}' />
    {% if product in cart.products.all %}
        In cart <button type='submit' class='btn btn-link'>Remove?</button>
    {% else %}
        <button type='submit'  class='btn btn-success'>Add to cart</button>
    {% endif %}
</form>