Products/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^product_list/', views.product_list_view, name='product_list_view'),
    url(r'^product_list/(?P<category_slug>[-\w]+)/$', views.product_list_view, name='product_list_view_by_category'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    
    
]

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_home, name='cart'),
    url(r'^update/$', views.cart_update, name='update'),
    url(r'^add/$', views.cart_add, name='add'),
    url(r'^cart/$', views.cart_remove, name='delate'),
    url(r'^wishlist/$', views.wishlist, name='wishlist'),

]

stylelure/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from shop import views
from accounts import views as accounts_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from addresses.views import checkout_address_create_view,address_update
from orders.views import overview
# from cart.views import checkout_home
from coupons.views import coupon_apply


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^account/',include('accounts.urls',namespace='accounts')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^contact/$', views.emailView, name='contact'),
    url(r'^address/$', address_update, name='address'),
    url(r'^address/add$', checkout_address_create_view, name='add_address'),
    url(r'^order/',include('orders.urls',namespace='order')),
    #url(r'^order/overview$', checkout_home, name='overview'),
    url(r'^apply/$',coupon_apply, name='apply'),
    url(r'^payment/',include('billing.urls',namespace='payment')),
    url(r'^contact/success$', views.successView, name='success'),
    url(r'^product/',include('Products.urls',namespace='Products')),
    url(r'^search/',include('search.urls',namespace='search')),
    # url(r'^review/', include('review.urls')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^wishlist/',include('wishlist.urls',namespace='wishlist')),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Products/models.py
from django.db import models
from django.utils import timezone
from colorfield.fields import ColorField
from django.db.models import Q
from django.urls import reverse

available_size_choices = (
    ('small', 'S'),
    ('medium', 'M'),
    ('large', 'L'),
    ('extraLarge', 'XL'),
)

class Category(models.Model):
    Category_name  = models.CharField(max_length=200,db_index=True,default='Other')
    slug  = models.SlugField(max_length=200, db_index=True,unique=True)


    class Meta:
        # ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'


    def __str__(self):
        return self.Category_name

    def get_absolute_url(self):
        return reverse('Products:product_list_by_category', args=[self.slug])



class Model_Category(models.Model):
    Model_Category_name  = models.CharField(max_length=200)
    slug  = models.SlugField(max_length=200,unique=True)


    class Meta:
        # ordering = ('name',)
        verbose_name = 'model_category'
        verbose_name_plural = 'model_categories'


    def __str__(self):
        return self.Model_Category_name

    def get_absolute_url(self):
        return reverse('Products:product_list_by_Model_category', args=[self.slug])


class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)

    def search(self, query):
        lookups = (Q(title__icontains=query) |
                  Q(description__icontains=query) |
                  Q(price__icontains=query) |
                  Q(tag__title__icontains=query)
                  )
        # tshirt, t-shirt, t shirt, red, green, blue,
        return self.filter(lookups).distinct()

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self): 
        return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id) # Product.objects == self.get_queryset()
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)

class Product(models.Model):
    title            = models.CharField(max_length=30, db_index=True)
    slug             = models.SlugField(blank=True, db_index=True )
    category         = models.ForeignKey(Category, related_name='products',default='Other')
    model_category   = models.ForeignKey(Model_Category, related_name='model_products')
    price            = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
    discounted_price = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
    # image         = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    short_description = models.TextField(blank=True)
    description      = models.TextField(blank=True)
    featured         = models.BooleanField(default=False)
    new_collection   = models.BooleanField(default=False)
    stock            = models.PositiveIntegerField(default=2)
    # available_color = ColorField(default='#FF0000')
    Manufacturer    = models.CharField(max_length=50)
    Occassion       = models.CharField(max_length=50)
    Season          = models.CharField(max_length=50)
    Gender          = models.CharField(max_length=50)
    available_size   = models.CharField(max_length=50)
    active           = models.BooleanField(default=True)
    created          = models.DateTimeField(auto_now_add=True)
    updated          = models.DateTimeField(auto_now=True)
    sku              = models.CharField(max_length=32, unique=True)

    objects = ProductManager()

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def product_count(self):
        return Product.category.objects.count()

    def get_absolute_url(self):
        # print(reverse('Products:product_detail', args=[self.id, self.slug]))
        return reverse('Products:product_detail', args=[self.id, self.slug])

    @property
    def name(self):
        return self.title

    def id(self):
        return self.id

class ProductImages(models.Model):
    product         = models.ForeignKey(Product,related_name='images',on_delete=models.CASCADE)
    image           = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    name            = models.CharField(max_length=30,null=True,blank=True)


class ProductColors(models.Model):
    product         = models.ForeignKey(Product,related_name='colors',on_delete=models.CASCADE)
    available_color = ColorField()

    def __str__(self):
        return self.available_color

Products/forms.py
from django import forms
from django.forms import ModelForm
# from django.forms.widgets import TextInput
from .models import Product

available_size_choices = (
    ('small', 'S'),
    ('medium', 'M'),
    ('large', 'L'),
    ('extraLarge', 'XL'),
)


class ProductForm(ModelForm):

    available_size  = forms.MultipleChoiceField( choices = available_size_choices,required=False)

    class Meta:
        model = Product
        fields= '__all__'
        # fields = '__all__'
        # widgets = {
        #     'color': TextInput(attrs={'type': 'color'}),
        # }

Products/views.py
from django.shortcuts import render,get_object_or_404
from .models import Product,ProductImages,Category
from cart.models import Cart
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products_list = Product.objects.filter(active=True)
    page = request.GET.get('page', 1)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products_list = products_list.filter(category=category)
    paginator = Paginator(products_list, 3)
    try:
        topics = paginator.page(page)
    except PageNotAnInteger:
        # fallback to the first page
        topics = paginator.page(1)
    except EmptyPage:
        # probably the user tried to add a page number
        # in the url, so we fallback to the last page
        topics = paginator.page(paginator.num_pages)
    context= {'category': category,'products_list':products_list,'categories': categories ,'topics':topics}
    return render(request,'products/product_list.html',context)


def product_list_view(request, category_slug=None):
    # import pdb; pdb.set_trace()
    category = None
    categories = Category.objects.all()
    products_list = Product.objects.filter(active=True)
    page = request.GET.get('page', 1)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products_list = products_list.filter(category=category)
    paginator = Paginator(products_list, 3)
    try:
        topics = paginator.page(page)
    except PageNotAnInteger:
        # fallback to the first page
        topics = paginator.page(1)
    except EmptyPage:
        # probably the user tried to add a page number
        # in the url, so we fallback to the last page
        topics = paginator.page(paginator.num_pages)
    context= {'category': category,'products_list':products_list,'categories': categories ,'topics':topics}
    return render(request,'products/product_list_view.html',context)

def product_detail(request,id, slug):
    instance = Product.objects.get_by_id(id)
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    size = instance.available_size
    if instance is None:
        raise Http404("Product doesn't exist")

    context = {
        'cart_obj':cart_obj,
        'object': instance,
        'object_size': size
    }

    print(size)
    return render(request, "products/detail.html", context)
# Create your views here.

Products/templates/products/detail.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static "css/product_detail.css" %}"rel="stylesheet">{% endblock %}
{% block content %}
<div class="details-product">
<div class="container">
  <div class="row">
    <div class="col-md-6">
       {% if object.images.count == 1 %}

         <img src="{{object.images.first.image.url}}" class="pd_75" align='center'>
        {% else %}
      <div class="slider slider-for">
        {% for j in "xx" %}
      	{% for i in object.images.all|slice:"1:4" %}

          <div><img src="{{ i.image.url }}" alt="logo image"></div>
        {% endfor %}
       {% endfor %}


      </div>
      <div class="slider pro-slider-nav">
      	{% for j in "xx" %}
      	{% for i in object.images.all|slice:"4:7" %}
        <div class="slick-slide">
          <div class="img"><img src="{{ i.image.url }}" alt="logo image"></div>
        </div>
        {% endfor %}
       {% endfor %}
      </div>
       {% endif%}
    </div>
    <div class="col-md-6">
      <div class="page-title">
        <div class="title-page">{{ object.title }}</div>
        <div class="active-page">
          <div class="sale">SALE</div>
          <div class="middle-star">
          <div class="middle-box">
            <div class="fill" style="width: 70%"></div>
          </div>
          </div>
          <!-- <div class="last-box"><i class="fa fa-pencil-square-o"></i></div>-->
        </div>
      </div>
      <div class="in-stock">
        <div class="title-center">${{ object.discounted_price }}<span>${{ object.price }}</span>
        	{% if object.active == True %}
        	<i class="fa fa-check-circle"><span>in stock</span></i>{% endif %}</div>
      </div>
      <div class="center-text">
        <p>{{ object.short_description }} </p>
      </div>
      <div class="bottom-text">
        <div class="text-1">
          <p>The model is wearing size: <span>S</span></p>
          | </div>
        <div class="text-2">
          <p> Model height: <span>170 cm</span></p>
        </div>
      </div>
      <div class="color-btn">
        <div class="btn-btn">
          <h3> Color</h3>
          <div class="main-box-color">
          	{% for  color in object.colors.all %}
            <div class="red-box" style="background-color:{{color.available_color}}"></div>
            {% endfor %}
          </div>
        </div>

        {% if 'a' in object_size or 'e' in object_size %}
        <div class="center-btn">
          <h3>Select size <span>size guide</span></h3>
          <div class="main-box">
            <div class="box {% if 'small' not in object_size %} disable {% endif %}">S</div>
            <div class="box {% if 'medium' not in object_size %} disable {%else%} {% endif %}">M</div>
            <div class="box {% if 'large' not in object_size %} disable{%else%} {% endif %}">L</div>
            <div class="box {% if 'extraLarge' not in object_size %} disable {% endif %}">XL</div>
          </div>
        </div>
        {% endif %}
      </div>
      <div class="Categories-box">
        <div class="address">
          <label>SKU :</label>
          <span>{{object.sku}}</span></div>
        <div class="address">
          <label>Categories :</label>
          <span>{{object.model_category}}</span></div>
        <div class="address">
          <label>tags : </label>
          <span>{{object.category}}</span></div>
        <div class="address">
          <label>share : </label>
          <div class="social-media">
            <ul>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
              <li  class="active"><a href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a href="#"><i class="fa fa-github"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    <form method='POST' action='{% url "cart:add" %}' class="form add_cart_form"> {% csrf_token %}
          <input type='hidden' name='product_id' value='{{ object.id }}' />
          <input type='hidden' class='color' name='selected_color' value="" />
          <input type='hidden' class='size' name='selected_size' value="" />
          <div class="button-cart">
       
               <button type='submit'  class='btn btn-left btn-success'>ADD TO CART</button>

      
          </div>
      </form>

       <form method='POST' action='{% url "wishlist:add" %}' class="form" id="add_wishlist_form"> {% csrf_token %}
          <input type='hidden' name='product_id' value='{{ object.id }}' />
          <input type='hidden' class='color' name='selected_color' value="" />
          <input type='hidden' class='size' name='selected_size' value="" />
         <div class="button-cart">
       

          <i class="fa fa-heart-o" id='wishlist_icon' ></i>
         
          
      </form>


    </div>
  </div>
</div>
</div>
<div class="description-box">
<div class="container">
  <div class="tab-menu">
    <ul>
      <li class="active"><a href="javascript:void(0);" id="description">Description</a></li>
      <li><a href="javascript:void(0);" id="review">reviews (3)</a>
    </ul>
  </div>
  <div class="description-box tab-detalis">

	<div class="upper-details">
		 <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
		<p>{{object.description }}</p>



	</div>
	<div class="more-information">
		<label>More Information</label>
	</div>
	<div class="information-box">
		<div class="information active"><label>Manufacturer</label><span>{{object.Manufacturer}}</span></div>
		<div class="information"><label>Occassion</label><span>{{object.Occassion}}</span></div>
		<div class="information active"><label>Gender</label><span>{{object.Gender}}</span></div>
		<div class="information "><label>Season</label><span>{{object.Season}}</span></div>
	</div>
 </div>
  <div class="review-box tab-detalis">
    <div class="row">
      <div class="col-md-7">
        <div class="review-slide">
         <div class="image-box"> <img src="{% static "images/review_1.png" %}" alt="logo image"> </div>
          <div class="right-box">
            <label>
            Richard L. Purdy
            <div class="star-box">
              <div class="fill" style="width: 70%"></div>
            </div>
            </label>
            <span>Nov 12, 2017, at 09:00</span>
            <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
          </div>
        </div>
        <div class="review-slide">
          <div class="image-box"> <img src="{% static "images/review_2.png" %}" alt="logo image"></div>
          <div class="right-box">
            <label>
            Richard L. Purdy
            <div class="star-box">
              <div class="fill" style="width: 70%"></div>
            </div>
            </label>
            <span>Nov 12, 2017, at 09:00</span>
            <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
          </div>
        </div>
        <div class="review-slide">
         <div class="image-box"> <img src="{% static "images/review_3.png" %}" alt="logo image"> </div>
          <div class="right-box">
            <label>
            Richard L. Purdy
            <div class="star-box">
              <div class="fill" style="width: 70%"></div>
            </div>
            </label>
            <span>Nov 12, 2017, at 09:00</span>
            <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
          </div>
        </div>
      </div>
      <div class="col-md-5">
        <div class="form-group">
          <label for="email">First  Name <span> * </span></label>
          <input type="email" class="form-control" id="exampleInputEmaill" aria-describedby="emailHelp" placeholder="Enter your name">
        </div>
        <div class="form-group">
          <label for="email">Phone <span> * </span></label>
          <input type="email" class="form-control" id="exampleInputEmaill" aria-describedby="emailHelp" placeholder="info@account.com">
        </div>
        <div class="form-group">
          <label for="email">Message <span> * </span></label>
          <textarea class="form-control" rows="9" id="comment" placeholder="Type your message here.."></textarea>
        </div>
        <div class="button-btn-box btn-star-box">
          <div class="rate">
            <label>Your rating:</label>
            <div class="star-box">
              <div class="fill" style="width: 70%"></div>
            </div>
          </div>
          <a href="#" class="btn-left">SUBMIT</a> </div>
      </div>
    </div>
  </div>

</div>
</div>
{% endblock %}

Products/templates/products/product_list.html
{% extends 'base_product.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static "css/product_detail.css" %}"rel="stylesheet">{% endblock %}

          {% block product__list %}
           <div class="product-listing">
        <div class="inner-listing">
          <div class="row">
             {% for product in topics %}
            <div class="col-md-4 col-6 mb-30">
             <div class="product_image">


            <img src="{{ product.images.first.image.url }}" alt='a'/>
              <div class="product_caption">
                <a href="{{product.get_absolute_url}}" >
                <div class="pc_1">{{product.title|truncatechars:15}}</div>
                <div class="pc_2">${{ product.price|floatformat }}</div>
                </a>
              </div>
  <div class="modal fade" id="a{{product.id}}" role="dialog">
    <div class="modal-dialog">
    
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Select Color and Size</h4>
        </div>
        <div class="modal-body">
         <div class="color-btn">
                <div class="btn-btn">
                  <h3> Color</h3>
                  <div class="main-box-color">
                    {% for  color in product.colors.all %}
                    <div class="red-box" style="background-color:{{color.available_color}}"></div>
                    {% endfor %}
                  </div>
                </div>
               
                {% if 'a' in product.available_size or 'e' in product.available_size %}
                <div class="center-btn">
                  <h3>Select size <span>size guide</span></h3>
                  <div class="main-box">
                    <div class="box  {% if 'small' not in product.available_size %} disable {% endif %}">S</div>
                    <div class="box {% if 'medium' not in product.available_size %} disable {%else%} {% endif %}">M</div>
                    <div class="box {% if 'large' not in product.available_size %} disable{%else%} {% endif %}">L</div>
                    <div class="box {% if 'extraLarge' not in product.available_size %} disable {% endif %}">XL</div>
                  </div>
                </div>
                {% endif %}
              </div>
        </div>
        <div class="modal-footer">
          <form method='POST' action='{% url "cart:add" %}' class="form add_cart_form"> {% csrf_token %}
            <input type='hidden' class="product_id" name='product_id' value='{{ product.id }}' />
            <input type='hidden' class='color' name='selected_color' value="" />
            <input type='hidden' class='size' name='selected_size' value="" />
          <button type="submit" class="btn btn-default">Confirm</button>
          </form>
        </div>
      </div>
      
    </div>
  </div>
              <div class="overlay-div text-center">
                <div class="overlay-content">
                  <div class="button_block">                   
                  </div>
                    <div class="add_to_cart" style="cursor: pointer"> 
                    <i class="pe-7s-cart"></i> ADD TO CART
                    <input type='hidden' class="product_id" name='product_id' value='{{ product.id }}' />
                  </div>
                </div>
              </div>

            </div>

          </div>
          {% endfor %}
     
    </div>

    {% if topics.has_other_pages %}
  <nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination">
      {% if topics.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ topics.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {% for page_num in topics.paginator.page_range %}
        {% if topics.number == page_num %}
          <li class="page-item active">
            <span class="page-link">
              {{ page_num }}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if topics.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ topics.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}
  </div>
</div>
    {% endblock product__list %}

Products/templates/products/product_list_view.html
{% extends 'base_product.html' %}
{% load static %}
{% block stylesheets %}
<link href="{% static "css/product_detail.css" %}"rel="stylesheet">{% endblock %}

{% block product__list %}
<div class="product-listing list-type">
            <div class="row">
             
         
           {% for product in topics %}
              <div class="col-12">
                <div class="shop-list-view">
                  <div class="product-item">
                   
                  <div class="product-image"> <img src="{{ product.images.first.image.url }}" alt='a'/></div>
                  </div>
                  <div class="product-item-details">
                    <div class="product-item-name"> 
                      <a href="{{product.get_absolute_url}}">{{product.title|truncatechars:45}} </a> 
                    </div>
                   
                    <div class="price-box"> <span class="price">${{ product.discounted_price }}</span> <del class="price old-price">${{ product.price|floatformat }}</del> </div>
                    <p>{{ product.short_description }}</p>
                    <div class="bottom-detail">
              <div class="color-btn">
                <div class="btn-btn">
                  <h3> Color</h3>
                  <div class="main-box-color">
                    {% for  color in product.colors.all %}
                    <div class="red-box" style="background-color:{{color.available_color}}"></div>
                    {% endfor %}
                  </div>
                </div>
               
                {% if 'a' in product.available_size or 'e' in product.available_size %}
                <div class="center-btn">
                  <h3>Select size <span>size guide</span></h3>
                  <div class="main-box">
                <div class="box  {% if 'small' not in product.available_size %} disable {% endif %}">S</div>
                    <div class="box {% if 'medium' not in product.available_size %} disable {%else%} {% endif %}">M</div>
                    <div class="box {% if 'large' not in product.available_size %} disable{%else%} {% endif %}">L</div>
                    <div class="box {% if 'extraLarge' not in product.available_size %} disable {% endif %}">XL</div>
                  </div>
                </div>
                {% endif %}
              </div>
                <form method='POST' action='{% url "cart:add" %}' class="form add_cart_form"> {% csrf_token %}
          <input type='hidden' name='product_id' value='{{ product.id }}' />
          <input type='hidden' class='color' name='selected_color' value="" />
          <input type='hidden' class='size' name='selected_size' value="" />
          <div class="button-cart">
         
               <button type='submit'  class='btn btn-left btn-success'>ADD TO CART</button>

         
          <a href="#"><i class="fa fa-heart-o"></i></a>
          </div>
      </form>
                      
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            
           
            </div>
             {% if topics.has_other_pages %}
  <nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination">
      {% if topics.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ topics.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {% for page_num in topics.paginator.page_range %}
        {% if topics.number == page_num %}
          <li class="page-item active">
            <span class="page-link">
              {{ page_num }}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if topics.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ topics.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}
          </div>
          {% endblock product__list%}